The chnages made in workflow to check if any deployment pre exists

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -106,5 +106,10 @@ jobs:
     - name: Deploy to EKS
       run: kubectl apply -f deployment.yaml
 
+    # Check if the deployment exists before restarting
+    - name: Check if deployment exists
+      run: |
+        kubectl get deployment flask-app -n flask-app || echo "Deployment flask-app not found"
+
     - name: Restart deployment to pull the latest image
       run: kubectl rollout restart deployment flask-app -n flask-app
